################################
# Site Settings
################################
lang        : "en"
logo        :
title       : Minimal Theme
description : Your awesome site
author      : Desired Persona
email       : your-email@domain.com
baseurl     : "" # the subpath of your site, e.g. /blog
url         : ""
date_format : "%-d %b %Y"
port        : 4000


################################
# Theme Settings
################################
theme       : minimal-jekyll-theme
permalink   : /:title/

collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Navigation Menus
header_navigation:
  - title: Documentation
    url: /docs/

  - title: Themes
    url: https://desiredpersona.com/themes/

  - title: About
    url: /about/

  - title: Blog
    url: /archive/

  - title: Contact
    url: mailto:you@example.com

footer_navigation:
  - title: privacy
    url: /privacy/

  - title: terms
    url: /terms/

# Markdown Settings
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Include/Exclude filetypes
include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: desired-persona-dev


################################
# Analytics Settings
################################
google_tag_manager: UA-XXXXXXXX-N


################################
# Jekyll Plugins
################################
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

# Jekyll SEO Tag Settings https://github.com/jekyll/jekyll-seo-tag
social:
  name: Joe Bloggs
  links:
    - https://twitter.com/username
    - https://plus.google.com/u/0/+username
    - https://www.facebook.com/username

twitter:
  username: Joe Bloggs

facebook:
  app_id:
  publisher:
  admins:

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:

# Jekyll Feed Settings https://github.com/jekyll/jekyll-feed
atom_feed:
    path: # Leave blank to use default (feed.xml)

# Jekyll Archives Settings https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
     - categories
     - tags
     - year
     - month
     - day
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'